<?php

namespace App\Entities\Enums;

abstract class TIPO_NOTIFICACAO
{
    const ATRASO_TRANSPORTE = 'ATRASO_TRANSPORTE';
    const AUSENCIA_TRANSPORTE = 'AUSENCIA_TRANSPORTE';
    const RENOVACAO_CADASTRO = 'RENOVACAO_CADASTRO';
    const MUDANCA_ROTA = 'MUDANCA_ROTA';
    const MUDANCA_MOTORISTA = 'MUDANCA_MOTORISTA';
    const MUDANCA_VEICULO = 'MUDANCA_VEICULO';
    const CONFIRMACAO_PRESENCA = 'CONFIRMACAO_PRESENCA';
}
